### ISSUE TITLE
Feature request: producer side connection pool

### ISSUE THREAD

**Issue by supervacuum** [go-stomp/stomp#10]
Hi, I am developing a simple STOMP-based command framework and I wondered if there is any plan to implement a connection pool. Happy to contribute code if willing to consider it for a merge.

**Comment by jjeffery** [comment]
Interesting idea. My initial reaction is that a connection pool might be better off in a separate package to keep the stomp package simple.

Have you had a look at the golang sync.Pool class? It might be of use to you.
