### ISSUE TITLE
How to detect if the connection is lost?

### ISSUE THREAD

**Issue by ecerichter** [go-stomp/stomp#112]
I'm writing a high performance microservice in Go, and I would like to keep the Stomp connection open as long as possible.
But in an event of server failure, how the microservice would detect that connection is dropped, and to start a to try to reopen?

**Comment by worg** [comment]
On error (network or otherwise) the subscription returns a message with non
nil error, you should check for that in your handler and reconnect if needed

**Comment by ecerichter** [comment]
Thanks, I've used a simple loop with a exponencial sleep time - if I did not get in 3 attemps, I'll try another server (3 servers, 3 times each server).
