### ISSUE TITLE
Stomp + ActiveMQ

### ISSUE THREAD

**Issue by ecerichter** [go-stomp/stomp#113]
How could I specify that a message shall be durable (and survive a server restart)?
I've tryied to add header "durable" with value "true", but no luck.

**Comment by worg** [comment]
There's no "durable" header in the STOMP spec, ActiveMQ has durable topics
as an extension, and needs to set client-id and subscriptionName per their
docs https://activemq.apache.org/stomp.html

**Comment by moredure** [comment]
@ecerichter "persistent" should be "true"

**Comment by ecerichter** [comment]
Yes, code last as:

err := getMqConn().Send("myaddr::myqueue", "text/plain", b, stomp.SendOpt.NoContentLength, stomp.SendOpt.Header("persistent", "true"))

And it works fine!
Thanks,

Edson
