### ISSUE TITLE
How to implement persistent subscriptions in the subscribe/publish mode(ActiveMQ).

### ISSUE THREAD

**Issue by zklaushhh** [go-stomp/stomp#115]
How to implement persistent subscriptions in the subscribe/publish mode.

**Comment by worg** [comment]
You can set the [`persistent`](https://activemq.apache.org/stomp#working-with-destinations-with-stomp) header with a [SendOption](https://pkg.go.dev/github.com/go-stomp/stomp/v3#SendOpt)

```go
conn.Send(`/some/queue`, `text/plain`, []byte(`my message`), SendOpt.Header(`persistent`, `true`)
```

The server must be configured to

**Comment by zklaushhh** [comment]
> You can set the [`persistent`](https://activemq.apache.org/stomp#working-with-destinations-with-stomp) header with a [SendOption](https://pkg.go.dev/github.com/go-stomp/stomp/v3#SendOpt)
> 
> ```go
> conn.Send(`/some/queue`, `text/plain`, []byte(`my message`), SendOpt.Header(`persistent`, `true`))
> ```
> 
> Assuming you're using an ActiveMQ server that supports the header

ok i will have a try，thanks u so much
