### ISSUE TITLE
Connect to STOMP server with path in URL

### ISSUE THREAD

**Issue by extbe** [go-stomp/stomp#116]
Hi there!

Does the library have a functionality to connect to STOMP server that have a URL path, not just host:port?

For example, I have a server that uses Spring + STOMP. The STOMP endpoint is `localhost:8080/ws`. Is it possible to connect to this endpoint?

**Comment by worg** [comment]
I'm not entirely familiar with spring+stomp but it seems it's stomp over websockets, am I right?
In that case you should be able to use `golang.org/x/net/websocket` Dial method to obtain a [`Conn`](https://pkg.go.dev/golang.org/x/net/websocket#Conn) that you can pass to [stomp.Connect](https://pkg.go.dev/github.com/go-stomp/stomp/v3#Connect)

something like this should work (you might need to adjust the origin and url protocols):
```go
        origin := "ws://localhost:8080"
	url := "ws://localhost:8080/ws"
	ws, err := websocket.Dial(url, "", origin)
	if err != nil {
		log.Fatal(err)
	}
	
	stompConn, err := stomp.Connect(ws)
	if err != nil {
		log.Fatal(err)
	}

	doSomethingWith(stompConn)
```

**Comment by extbe** [comment]
Works like a charm, thanks!

**Comment by worg** [comment]
Sorry @alwindoss I'm having a hard time following your comment, what are you trying to achieve? and what webserver are you talking about?
