### ISSUE TITLE
Unable to receive replies

### ISSUE THREAD

**Issue by marlongerson** [go-stomp/stomp#125]
How do we receive replies after specifying the `reply-to` header? As I understand, when a client specifies the `reply-to` header in a `Send`, the client will automatically be subscribed to that `reply-to` destination.

Currently, the reply is ignored: https://github.com/go-stomp/stomp/blob/master/conn.go#L337

How are we supposed to receive the reply?

**Comment by worg** [comment]
You need to have an existing subscription to the destination in `reply-to`
header before sending messages using it. It's good to note, there's nothing
in the [spec](https://stomp.github.io/stomp-specification-1.2.html)
indicating an automatic subscription on `reply-to` usage, AFAICT that's a
nonstandard extension from some servers (ActiveMQ being one of them)
