### ISSUE TITLE
How to prevent closing the connection

### ISSUE THREAD

**Issue by iWebi** [go-stomp/stomp#17]
Do we need to fetch new connection every time you send a message on connection?
As the document mentioned, we see that underlying connection is closed when there is a failure in sending the message.

```
var conn *stomp.Conn
if conn, err = stomp.Dial("tcp",
        Broker.URI,
        stomp.ConnOpt.Login(Broker.User, Broker.Password)); err != nil {
        panic(fmt.Sprintf("Could not connect to ActiveMQ using brokerUri %v. Can not continue.", Broker.URI))
    }
And else where in the code, I use the above "global" connection instances to send messages.
if err := conn.Send(queue, "text/plain", []byte(message)); err != nil {
            log.Printf("Failed to send message to Queue %v.  Error is %v, Payload is %v", queue, err.Error(), message)
            return err
        }
```

But during failures, I see that the connection is closed and subsequent Send call fails. 
Is there a way to maintain the connection even during failures? or do we need to fetch a new connection every time one wants to send messages?

**Comment by dahankzter** [comment]
I create a new connection whenever I encounter a panic from "connection closed".
It is not ideal... Mayne some re-connect functionality can fix it.

**Comment by worg** [comment]
Hi I think it's better to handle the reconnect [and check for connection status before sending, to prevent panics] manually, because there can be many different scenarios when you would want to wait before reconnect due to fair use rules [if your broker has one], although providing a reconnect method would be convenient as a user of go-stomp it could cause some heavy loads on the brokers.

**Comment by dahankzter** [comment]
I get the disconnected status panic not when sending but when subscribing to queues. There is no real way to check anything since I am just listening. I have to recover the panic and create a new connection.

**Comment by worg** [comment]
are you using heartbeats? if so, have you tried to increase the read heartbeat time?

**Comment by dahankzter** [comment]
Dial works fine, I get messages fine for a while but after a period of inactivity I tend to get this panic.

I was using heartbeats but didn't think it made any difference. Perhaps I should reapply them.

**Comment by worg** [comment]
try increasing read heartbeat time
