### ISSUE TITLE
processLoop can terminate w/o surfacing any errors.

### ISSUE THREAD

**Issue by jimrobinson** [go-stomp/stomp#18]
If the underlying connection to a producer goes away, say because the STOMP server is forcibly restarted w/o any clean shutdown, then processLoop in conn.go can terminate w/o any errors being surfaced (e.g., the case f, ok := <-c.readCh: will get a "connection close" error and terminate the processLoop).  If this happens any producer with an open connection can keep sending requests, and if those requests are set for auto ack they will silently fail until the writeCh buffer is filled at which point I believe the writes will just stall.

I think one solution to this problem is to incorporate the MustDisconnect method in https://github.com/go-stomp/stomp/issues/13 and to then have a "defer c.MustDisconnect()" in processLoop before launching the for {} loop.

**Comment by jimrobinson** [comment]
{code}
diff --git a/conn.go b/conn.go
index 722bf96..b91001e 100644
--- a/conn.go
+++ b/conn.go
@@ -211,6 +211,8 @@ func processLoop(c *Conn, writer *frame.Writer) {
        var writeTimeoutChannel <-chan time.Time
        var writeTimer *time.Timer
 
+       defer c.MustDisconnect()
+
        for {
                if c.readTimeout > 0 && readTimer == nil {
                        readTimer := time.NewTimer(c.readTimeout)
@@ -367,6 +369,22 @@ func (c *Conn) Disconnect() error {
        return c.conn.Close()
 }
 
+// MustDisconnect will disconnect 'ungracefully' from the STOMP server.
+// This method should be used only as last resort when there are fatal
+// network errors that prevent to do a proper disconnect from the server.
+func (c *Conn) MustDisconnect() error {
+       if c.closed {
+               return nil
+       }
+
+       // just close readCh and writeCh
+       // close(c.readCh)
+       close(c.writeCh)
+
+       c.closed = true
+       return c.conn.Close()
+}
+
 // Send sends a message to the STOMP server, which in turn sends the message to the specified destination.
 // If the STOMP server fails to receive the message for any reason, the connection will close.
 //
{code}

**Comment by steven-ma** [comment]
when "case <-readTimeoutChannel:",  then processLoop in conn.go can terminate, and Disconnect() will never  retrun. That means i must use MustDisconnect() when read timeout?

**Comment by worg** [comment]
@steven-ma indeed, I haven't had time to incorporate @jimrobinson patch but that should fix it
