### ISSUE TITLE
How to set heartbeat correctly? 

### ISSUE THREAD

**Issue by ltzMaxwell** [go-stomp/stomp#32]
I set heartbeat to different values  with 

stomp.ConnOpt.HeartBeat(1*time.Second, 1*time.Second)

but still got "Error message : read timeout" ,  or "Error message : connection closed"

**Comment by worg** [comment]
The server you're connecting to is ready to send/receive heartbeats?

**Comment by rp42** [comment]
I ran into heartbeat problems with Active MQ (5.14.5). Without specifying any go-stomp heartbeat options, both the CONNECT and CONNECTED frames had the following header:
heart-beat:60000,60000

However, no further data is seen to come from ActiveMQ and go-stomp times out. I'm wondering if any configuration is needed to enable this in ActiveMQ, or if their STOMP implementation has a bug.

**Comment by worg** [comment]
@rp42 as stated in the documentation… https://godoc.org/github.com/go-stomp/stomp
```
   // HeartBeat is a connect option that allows the client to specify
    // the send and receive timeouts for the STOMP heartbeat negotiation mechanism.
    // The sendTimeout parameter specifies the maximum amount of time
    // between the client sending heartbeat notifications from the server.
    // The recvTimeout paramter specifies the minimum amount of time between
    // the client expecting to receive heartbeat notifications from the server.
    // If not specified, this option defaults to one minute for both send and receive
    // timeouts.
```

**Comment by rp42** [comment]
Thanks for the clarification. TBH, my problem looked like an issue with ActiveMQ's STOMP implementation rather than an issue with go-stomp. Maybe as there are TCP keep-alives, ActiveMQ thinks it doesn't need to keep up its side of the deal with the STOMP protocol keep-alives.

**Comment by worg** [comment]
So is on the AMQ side, can we close the issue?

**Comment by rp42** [comment]
OK by me. The OP doesn't say if they're using AMQ or something else though,
