### ISSUE TITLE
Don't encoding headers in Stomp V1.0

### ISSUE THREAD

**Issue by ghost** [go-stomp/stomp#34]
According to the Stomp 1.1 spec headers should be encoded to escape carriage returns, line feeds and colons. (see: https://stomp.github.io/stomp-specification-1.1.html#Value_Encoding) This is a change from V1.0 where there was no such stipulation. However the headers appear to be encoded always regardless of the version of the server. Am I understanding the spec correctly and if so is this a bug?

**Comment by jjeffery** [comment]
I have not checked the specs before writing this, but if I remember correctly, the 1.0 spec makes no mention of what to do if the headers contains white space or colon. Given that it is not specified, it is not very safe to send headers containing these characters when using the 1.0 protocol.

Given, however, that the 1.0 spec makes no mention of what to do in this case, it seems reasonable to adopt the 1.1 behaviour.

**Comment by OrangeSword** [comment]
The header in question is message-id which the Apache ActiveMQ java package is generating with unescaped colons.  How can I use go-stomp to communicate V1.0 apacheMQ server if it is not expecting the colons to be escaped in the message-id.

**Comment by worg** [comment]
ping
