### ISSUE TITLE
Panic: send on closed channel

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [go-stomp/stomp#44]
The function Send in stomp/conn.go (line 412) is sometimes raising a panic when writing to a queue.
Here are two images of the panic. My program is using termUI which is the reason why the stacktrace is not that readable. It seems not really to be reproduceable.

![panic_activemq_stomp](https://user-images.githubusercontent.com/6683555/45082561-e7606680-b0f9-11e8-9ccf-8bba282673b6.png)
![panic_activemq_stomp_2](https://user-images.githubusercontent.com/6683555/45082622-03640800-b0fa-11e8-95ba-7ef7af691010.png)

**Comment by Fjolnir-Dvorak** [comment]
Could be caused by #43

**Comment by worg** [comment]
@Fjolnir-Dvorak can we close the issue?
