### ISSUE TITLE
v2 doesnt support semantic versioning

### ISSUE THREAD

**Issue by vivlis** [go-stomp/stomp#46]
hi 
getting error when trying new 1.11 module versioning

go.mod
> require (
> 	github.com/go-stomp/stomp v2.0.0
> )

\go.mod:5: invalid module version "v2.0.0": unknown revision v2.0.0

**Comment by alkaliphile** [comment]
Is all that's needed to fix this to publish a new release using 2.0.0. for the tag? I could submit a PR for that.

**Comment by vivlis** [comment]
Hi __

It was released as in 1.11
https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more
example 
_module example.com/m

require (
	golang.org/x/text v0.3.0
	gopkg.in/yaml.v2 v2.1.0
)_

https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
thanks

**Comment by sinofool** [comment]
+1
Please create v2.0.0 tag.

**Comment by jjeffery** [comment]
Tag created: v2.0.1. I did not use v2.0.0, as that might be easily confused with the v2.0 tag.
