### ISSUE TITLE
can not send with expires

### ISSUE THREAD

**Issue by jeek120** [go-stomp/stomp#47]
followed code can send
`w.Send("/queue/room_" +  room_no, "", bs)`

but followed code can not send
`w.Send("/queue/room_" +  room_no, "", bs, stomp.SendOpt.Receipt, stomp.SendOpt.Header("expires", "2049-12-31 23:59:59" /*time.Unix(end,0).Format("2006-01-02 15:04:05")*/ )/*, stomp.SendOpt.Header("priority", fmt.Sprintf("%d", p))*/)`

ActiceMq 5.15.6
`docker run -dt -P webcenter/activemq`

**Comment by hanjm** [comment]
@jeek120  the header "expires" value is the milliseconds timestamp.  see https://github.com/apache/activemq/blob/9abe2c6f97c92fc99c5a2ef02846f62002a671cf/activemq-stomp/src/test/java/org/apache/activemq/transport/stomp/StompTimeStampingBrokerPluginTest.java#L94

```
strconv.FormatInt(time.Now().Add(yourMessageTimeoutDuration).UnixNano()/1e6, 10)
```
