### ISSUE TITLE
not able to run client_test in example folder

### ISSUE THREAD

**Issue by prisonjun** [go-stomp/stomp#48]
I tried to run the client_test, it always returns error message "failed to send to server".
The root cause is in this line: err = conn.Send(*queueName, "text/plain", []byte(text), nil), you pass a nil option to Send method, and in the inner function createSendFrame, it will returns error if there is nil option.

So I think below is the fix point:
1. In the main.go file of client_test folder, go to function sendMessages, do the below change:
err = conn.Send(*queueName, "text/plain", []byte(text), nil) --> err = conn.Send(*queueName, "text/plain", []byte(text))
2. in conn.go file, go to function createSendFrame, do the below change:
		if opt == nil {
			return nil, ErrNilOption
		}
               -->
		if opt == nil {
			continue;
		}

**Comment by worg** [comment]
Yup, that's an error, I'll see into it and maybe push a fix in the coming days
