### ISSUE TITLE
Impossible to remove durable subscription in ActiveMQ

### ISSUE THREAD

**Issue by fpob** [go-stomp/stomp#50]
In ActiveMQ client must send two unsubscribe messages to remove durable subscription [[stackoverflow](https://stackoverflow.com/a/30537966)].

```
UNSUBSCRIBE
destination:/topic/MyTopic

^@

UNSUBSCRIBE
destination:/topic/MyTopic
activemq.subscriptionName:MySubscriptionName

^@
```
First unsubscribe make subscription inactive and second removes subscription. But because of condition at [subscription.go L63-65](https://github.com/go-stomp/stomp/blob/master/subscription.go#L63-L65) is impossible to send unsubscribe twice.

**Comment by worg** [comment]
The current behavior is right according to the [STOMP SPEC](https://stomp.github.io/stomp-specification-1.2.html#UNSUBSCRIBE)

**Comment by worg** [comment]
Closing as WONTFIX
