### ISSUE TITLE
Properly way to check for closed connection

### ISSUE THREAD

**Issue by ltpquang** [go-stomp/stomp#51]
Hi there, is there any way to check if a `Conn` is valid before sending the message? I'm currently doing as follow
```
err := conn.Send(queueName, "text/plain", message)
if err != nil && err.Error() == "connection already closed" {
	// report error
}
```
The `Conn` struct has `closed` property but since it is not exposed and have no access function, I have no way to check the connection before sending.

**Comment by worg** [comment]
Currently there's no other way, because there might happen that a frame fails [therefore closing the connection according to the spec] during the sending of the message, even if we exposed the closed property it might fail after the closed check and before the actual sending of the frame.

**Comment by tahseenjamal** [comment]
You can unmarshal Conn to a struct similar to that of Conn and then read the bool closed value. So no need to be dependent on 'closed' to be exposed
