### ISSUE TITLE
Monitor incoming frames

### ISSUE THREAD

**Issue by pstibrany** [go-stomp/stomp#60]
Is there a way to monitor incoming frames from the code? Eg. by registering function that can then log the frame?

**Comment by worg** [comment]
No, currently there's no option to handle that use case, I wonder why using the Message type doesn't work for your use case? The frame can be rebuilt from the Message.

**Comment by pstibrany** [comment]
Two days ago it felt like having that ability would help me see what I was doing wrong with my subscriber registrations. Of course that's not true... my client would not receive such messages in the first place. Let's close this and pretend I have never asked the question :)
