### ISSUE TITLE
Release the version with MsgSendTimeout

### ISSUE THREAD

**Issue by mmierzwa** [go-stomp/stomp#70]
When this change - https://github.com/go-stomp/stomp/commit/3e3ea3f82edd4c5d906dc7fc0d1702be4a91b4b0 - is gonna be released?
Having configurable timeouts is crucial from the reliability perspective in any distributed system...

**Comment by worg** [comment]
Sorry for the delay I'm releasing it now

**Comment by worg** [comment]
2.0.4 released

**Comment by mmierzwa** [comment]
Thank you @worg !
