### ISSUE TITLE
use Apache license text to display on pkg.go.dev

### ISSUE THREAD

**Issue by jba** [go-stomp/stomp#71]
This module's contents doesn't show up on pkg.go.dev because:
1. The license filename isn't recognized (see https://pkg.go.dev/license-policy).
2. The license contents would not be recognized. (**Not legal advice:** You've copied the Apache 2.0 _header_, designed to be added to the top of every file; it is not appropriate for the whole module.)

If you change the filename and use the [exact text of the Apache 2.0 license](https://opensource.org/licenses/Apache-2.0), pkg.go.dev will show your module doc and readme.

**Comment by worg** [comment]
working on it…
@jjeffery are you ok with me adding the correct license file and add an authors list?

**Comment by jjeffery** [comment]
Fine with me.
