### ISSUE TITLE
Provide support for SSL connections

### ISSUE THREAD

**Issue by vkuznet** [go-stomp/stomp#74]
Hi,
I'm interested in support for Stomp SSL connection which is required in our infrastructure. The Python client [1] provides the ability to authentication clients with certificates. It would be nice if the stomp Go module will support this as well.
Thanks,
Valentin

[1] https://github.com/jasonrbriggs/stomp.py/blob/dev/stomp/connect.py#L65

**Comment by worg** [comment]
Hi!
Yo should be able to use the [Connect](https://godoc.org/gopkg.in/stomp.v1#Connect) method with an underlying TLS connection (https://godoc.org/crypto/tls#Conn)

**Comment by vkuznet** [comment]
thanks for pointers, I managed the code to work with tls connection.
