### ISSUE TITLE
Read buffer size hard coded

### ISSUE THREAD

**Issue by mkhanali** [go-stomp/stomp#75]
We can't read any message greater than 4096 because read `bufferSize` is hard coded, not configurable. 

http://gitlab.trad.tradestation.com/webapi/nitro/blob/master/vendor/github.com/go-stomp/stomp/frame/reader.go#L34

`NewReaderSize` exist in frame.go but not used here. 
https://github.com/go-stomp/stomp/blob/master/conn.go#L73

Is there any work around to increase the read buffer size?

**Comment by worg** [comment]
This could be implemented as a new Options, like read and write channel capacity.
https://github.com/go-stomp/stomp/blob/master/conn_options.go#L153
PRs are always welcome

**Comment by mkhanali** [comment]
@worg Plz look at the pull request
