### ISSUE TITLE
Use of Server for production? 

### ISSUE THREAD

**Issue by cameronelliott** [go-stomp/stomp#86]
Hello, I am very happy to have discovered *go-stomp* 😄 
It looks like a very nice package.

Even though it is not mentioned in the README, I see there is a server package,
and the stompd cmd.
Is there a reason the server isn't mentioned in the README?

@worg @jjeffery 
Is anyone regularly using the server in any kind of production usage?

I am considering trying to add Web-STOMP support to the server, but I'd like to get any feedback about it's state and the server todo-list if possible.

Thank you in advance for any feedback about the server, whether it has worked for you, or if you think it is working okay or not.

Thanks,
Cameron

**Comment by worg** [comment]
Sorry for the late reply.The server is not production grade, AFAICT no one is using it for production loads.Of course you're free to build on it to your own needs.On Nov 6, 2020 05:01, Cameron Elliott <notifications@github.com> wrote:

Hello, I am very happy to have discovered go-stomp 😄

Even though it is not mentioned in the README, I see there is a server package,

and the stompd cmd.

Is there a reason the server isn't mentioned in the README?

Is anyone regularly using the server in any kind of production usage?

I am considering trying to add Web-STOMP support to the server, but I'd like to get any feedback about it's state and todo-list if possible.

Thanks,

Cameron
