### ISSUE TITLE
Content-length header suppression for sending TextMessages to ActiveMQ?

### ISSUE THREAD

**Issue by paulCodes** [go-stomp/stomp#9]
Is there a way to suppress/remove the content-length header currently? I ask this because ActiveMQ uses the content-length header to determine whether to store a message as TextMessage or BytesMessage. When using a Stomp to send a TextMessage to a Stomp consumer there isn't a problem but when sending to ActiveMQ and consumed by ActiveMQ the ability marshal the incoming message becomes a bit difficult because ActiveMQ stores the message as a ByteMessage when the consumer is expecting a TextMessage. 

Thanks

**Comment by jjeffery** [comment]
I think this feature has been asked for before, for the same reason. I have been thinking of making some breaking changes to this library, and this could be a good place to fork off a V2. Would you be interested in that?

The changes I have been thinking of are not huge, but they are breaking non the less, and I have absolutely no idea how many people are using this library.

What I have in mind is to make use of the pattern Dave Cheney described in his blog post "Functional options for friendly APIs" http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

So if we went with this option, then the Conn.Send method could be

```go
func (c *Conn) Send(destination, contentType string, body []byte, options ...func(*Conn)) error {
	// implementation here
}
```

So then the code to send without content length would look something like this:

```go
var c *stomp.Conn

// initialize c here

// send a message with content length (the default)
c.Send("queue-name", "text/plain", []byte("text message"))

// send a mesage without content length
c.Send("queue-name", "text/plain", []byte("text message"), stomp.SuppressContentLength)

// send a message without content length and require a receipt
c.Send("queue-name", "text/plain", []byte("text message"), 
    stomp.SuppressContentLength,
    stomp.ReceiptRequired)
```

So options for sending might include:

* stomp.SuppressContentLength
* stomp.ReceiptRequired
* stomp.CustomHeader(name, value string)

What do you think?

**Comment by paulCodes** [comment]
I like that. Very clean. Would you want to implement something temporary while working on v2? Like add a header that could remove the content length? I have a wip on my forked repo that I could PR for you if it would help.

**Comment by jjeffery** [comment]
By all means submit a PR if you have a solution. 

Be aware, however, that I have pushed the new API to the master branch now. It has the functionality you are asking for. If you have the time and inclination to look at it, I would welcome your feedback.

If you want to send a message with no content-length:

```go

// send without content-length
err := conn.Send("/queue/destination", "text/plain", []byte("this is the body),
                stomp.SendOpt.NoContentLength)

// send without content-length and another custom header
err = conn.Send("/queue/destination", "text/plain", []byte("this is the body),
                stomp.SendOpt.NoContentLength,
                stomp.SendOpt.Header("x-custom-header", "some value")


```

**Comment by paulCodes** [comment]
I went ahead and pulled down v2 and it is working perfectly. Thanks!
